_core:
  default_config_hash: 1SNdA25INsV5YjlgAJtfC-6AM8VcWe_00xneMLb2yFg
langcode: hu
message: '@site jelenleg karbantartás alatt áll, tartalma hamarosan újra elérhető lesz. Addig is köszönjük a türelmet.'
